version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: anp1993/taski_backend
    build: ./backend/
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db
  frontend:
    image: anp1993/taski_frontend
    env_file: .env
    build: ./frontend/
    volumes:
      - static_volume:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    image: anp1993/taski_gateway
    build: ./gateway/
    volumes:
      - static_volume:/staticfiles
    ports:
      - 8000:80 